// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: parser.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VkGroupId     string                 `protobuf:"bytes,1,opt,name=vk_group_id,json=vkGroupId,proto3" json:"vk_group_id,omitempty"`
	VkAccessToken string                 `protobuf:"bytes,2,opt,name=vk_access_token,json=vkAccessToken,proto3" json:"vk_access_token,omitempty"`
	MaxPosts      int32                  `protobuf:"varint,3,opt,name=max_posts,json=maxPosts,proto3" json:"max_posts,omitempty"`
	Reindex       bool                   `protobuf:"varint,4,opt,name=reindex,proto3" json:"reindex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetVkGroupId() string {
	if x != nil {
		return x.VkGroupId
	}
	return ""
}

func (x *ParseRequest) GetVkAccessToken() string {
	if x != nil {
		return x.VkAccessToken
	}
	return ""
}

func (x *ParseRequest) GetMaxPosts() int32 {
	if x != nil {
		return x.MaxPosts
	}
	return 0
}

func (x *ParseRequest) GetReindex() bool {
	if x != nil {
		return x.Reindex
	}
	return false
}

type ParseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedPosts int32                  `protobuf:"varint,4,opt,name=processed_posts,json=processedPosts,proto3" json:"processed_posts,omitempty"`
	IndexedChunks  int32                  `protobuf:"varint,5,opt,name=indexed_chunks,json=indexedChunks,proto3" json:"indexed_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ParseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ParseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseResponse) GetProcessedPosts() int32 {
	if x != nil {
		return x.ProcessedPosts
	}
	return 0
}

func (x *ParseResponse) GetIndexedChunks() int32 {
	if x != nil {
		return x.IndexedChunks
	}
	return 0
}

var File_parser_proto protoreflect.FileDescriptor

const file_parser_proto_rawDesc = "" +
	"\n" +
	"\fparser.proto\x12\x06parser\"\x8d\x01\n" +
	"\fParseRequest\x12\x1e\n" +
	"\vvk_group_id\x18\x01 \x01(\tR\tvkGroupId\x12&\n" +
	"\x0fvk_access_token\x18\x02 \x01(\tR\rvkAccessToken\x12\x1b\n" +
	"\tmax_posts\x18\x03 \x01(\x05R\bmaxPosts\x12\x18\n" +
	"\areindex\x18\x04 \x01(\bR\areindex\"\xaa\x01\n" +
	"\rParseResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12'\n" +
	"\x0fprocessed_posts\x18\x04 \x01(\x05R\x0eprocessedPosts\x12%\n" +
	"\x0eindexed_chunks\x18\x05 \x01(\x05R\rindexedChunks2E\n" +
	"\x06Parser\x12;\n" +
	"\fStartParsing\x12\x14.parser.ParseRequest\x1a\x15.parser.ParseResponseB\x1fZ\x1dgithub.com/pulse-fetch/protosb\x06proto3"

var (
	file_parser_proto_rawDescOnce sync.Once
	file_parser_proto_rawDescData []byte
)

func file_parser_proto_rawDescGZIP() []byte {
	file_parser_proto_rawDescOnce.Do(func() {
		file_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parser_proto_rawDesc), len(file_parser_proto_rawDesc)))
	})
	return file_parser_proto_rawDescData
}

var file_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parser_proto_goTypes = []any{
	(*ParseRequest)(nil),  // 0: parser.ParseRequest
	(*ParseResponse)(nil), // 1: parser.ParseResponse
}
var file_parser_proto_depIdxs = []int32{
	0, // 0: parser.Parser.StartParsing:input_type -> parser.ParseRequest
	1, // 1: parser.Parser.StartParsing:output_type -> parser.ParseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parser_proto_init() }
func file_parser_proto_init() {
	if File_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parser_proto_rawDesc), len(file_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parser_proto_goTypes,
		DependencyIndexes: file_parser_proto_depIdxs,
		MessageInfos:      file_parser_proto_msgTypes,
	}.Build()
	File_parser_proto = out.File
	file_parser_proto_goTypes = nil
	file_parser_proto_depIdxs = nil
}
