// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: searcher.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []float32              `protobuf:"fixed32,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_searcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_searcher_proto_rawDescGZIP(), []int{0}
}

func (x *InputRequest) GetItems() []float32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type OutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PossAnswers   []string               `protobuf:"bytes,1,rep,name=possAnswers,proto3" json:"possAnswers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	mi := &file_searcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_searcher_proto_rawDescGZIP(), []int{1}
}

func (x *OutputResponse) GetPossAnswers() []string {
	if x != nil {
		return x.PossAnswers
	}
	return nil
}

var File_searcher_proto protoreflect.FileDescriptor

const file_searcher_proto_rawDesc = "" +
	"\n" +
	"\x0esearcher.proto\x12\x03api\"$\n" +
	"\fInputRequest\x12\x14\n" +
	"\x05items\x18\x01 \x03(\x02R\x05items\"2\n" +
	"\x0eOutputResponse\x12 \n" +
	"\vpossAnswers\x18\x01 \x03(\tR\vpossAnswers2A\n" +
	"\bSearcher\x125\n" +
	"\vProcessData\x12\x11.api.InputRequest\x1a\x13.api.OutputResponseB\x1fZ\x1dgithub.com/pulse-fetch/protosb\x06proto3"

var (
	file_searcher_proto_rawDescOnce sync.Once
	file_searcher_proto_rawDescData []byte
)

func file_searcher_proto_rawDescGZIP() []byte {
	file_searcher_proto_rawDescOnce.Do(func() {
		file_searcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searcher_proto_rawDesc), len(file_searcher_proto_rawDesc)))
	})
	return file_searcher_proto_rawDescData
}

var file_searcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_searcher_proto_goTypes = []any{
	(*InputRequest)(nil),   // 0: api.InputRequest
	(*OutputResponse)(nil), // 1: api.OutputResponse
}
var file_searcher_proto_depIdxs = []int32{
	0, // 0: api.Searcher.ProcessData:input_type -> api.InputRequest
	1, // 1: api.Searcher.ProcessData:output_type -> api.OutputResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_searcher_proto_init() }
func file_searcher_proto_init() {
	if File_searcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searcher_proto_rawDesc), len(file_searcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searcher_proto_goTypes,
		DependencyIndexes: file_searcher_proto_depIdxs,
		MessageInfos:      file_searcher_proto_msgTypes,
	}.Build()
	File_searcher_proto = out.File
	file_searcher_proto_goTypes = nil
	file_searcher_proto_depIdxs = nil
}
